app = "schedulo-web"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[build.args]
  BUILT_NEXT_PUBLIC_WEBAPP_URL = "https://schedulo-web.fly.dev"

[env]
  API_PORT = "5555"
  PORT = "3000"
  IS_E2E = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false   # keep the app up
  min_machines_running = 1     # ensure at least one machine stays running

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory = "8gb"
